name: intake-erddap
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - dask
  - pandas
  - erddapy
  - panel
  - appdirs
  - intake
  - intake-xarray>=0.6.1
  - pip
  - pip:
    - cf-pandas
